name: helloworld
on: workflow_dispatch
jobs:
  check1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hellow world"
          echo "second line printed"
        
