name: thirdWF
on: 
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  job1-build:
   runs-on: ubuntu-latest
   steps:
     - name: echo command
       run: echo "building app"
